AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 10
    Environment:
      Variables:
        API_KEY: 9733bfa8b6384fe885593199c8a846192bddb4d9f9a649689c470b44329afe9a

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        openapi: '3.0'
        info:
          title: !Sub ${AWS::StackName}-HttpApi
          version: '1.0'
        paths:
          /{deviceId}:
            get:
              responses: {}
            put:
              responses: {}
          /ack-operate/{deviceId}:
            get:
              responses: {}
      FailOnWarnings: true
  DeviceStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  GetDeviceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-GetDeviceFunction
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: GetDeviceFunction
      CodeUri: src/device-handler-function
      Handler: index.getHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 2
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref DeviceStatusTable
      Events:
        HttpApiGETdeviceId:
          Type: HttpApi
          Properties:
            Path: /{deviceId}
            Method: GET
            ApiId: !Ref HttpApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
      Environment:
        Variables:
          TABLE_NAME: !Ref DeviceStatusTable
          TABLE_ARN: !GetAtt DeviceStatusTable.Arn
  PutDeviceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-PutDeviceFunction
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: PutDeviceFunction
      CodeUri: src/device-handler-function
      Handler: index.putHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 2
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref DeviceStatusTable
      Events:
        HttpApiPUTdeviceId:
          Type: HttpApi
          Properties:
            Path: /{deviceId}
            Method: PUT
            ApiId: !Ref HttpApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
      Environment:
        Variables:
          TABLE_NAME: !Ref DeviceStatusTable
          TABLE_ARN: !GetAtt DeviceStatusTable.Arn
  AckOperateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-AckOperateFunction
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: AckOperateFunction
      CodeUri: src/device-handler-function
      Handler: index.ackOperateHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 2
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref DeviceStatusTable
      Environment:
        Variables:
          TABLE_NAME: !Ref DeviceStatusTable
          TABLE_ARN: !GetAtt DeviceStatusTable.Arn
      Events:
        HttpApiGETackoperatedeviceId:
          Type: HttpApi
          Properties:
            Path: /ack-operate/{deviceId}
            Method: GET
            ApiId: !Ref HttpApi
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
  GetDeviceFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: GetDeviceFunction
    Properties:
      RetentionInDays: 14
      LogGroupName: !Join
        - ''
        - - /aws/lambda/
          - !Ref GetDeviceFunction
  PutDeviceFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: PutDeviceFunction
    Properties:
      RetentionInDays: 14
      LogGroupName: !Join
        - ''
        - - /aws/lambda/
          - !Ref PutDeviceFunction
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name
    Default: iot-stack
  EnvironmentTagName:
    Type: String
    Description: Environment Name
    Default: dev